// Módulo: Cue Sheet — turns the Set's REAL cue points into a mixtape cue sheet (.cue / .txt),
// written to storageDirectory. Times are computed from beats at the current tempo (stated
// honestly: a fixed-tempo mapping; tempo automation isn't readable via the SDK).
import { getStorageDir } from "../../core/storage.js";
import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join } from "node:path";

export class ToolRegistry {
  private handlers = new Map();
  definitions: any[] = [];
  register(def: any, handler: any) { this.definitions.push(def); this.handlers.set(def.name, handler); }
  async execute(name: string, args: any, song: any) {
    const h = this.handlers.get(name);
    if (!h) return { success: false, error: `Unknown: ${name}` };
    try { return await h(args, song); }
    catch (err: any) { return { success: false, error: err.message || String(err) }; }
  }
  getDefinitionsJson() { return this.definitions; }
}

function fmtCue(sec: number): string {
  const mm = Math.floor(sec / 60), ss = Math.floor(sec % 60), ff = Math.floor((sec % 1) * 75);
  return `${String(mm).padStart(2, "0")}:${String(ss).padStart(2, "0")}:${String(ff).padStart(2, "0")}`;
}
function fmtTxt(sec: number): string {
  const mm = Math.floor(sec / 60), ss = Math.floor(sec % 60);
  return `${String(mm).padStart(2, "0")}:${String(ss).padStart(2, "0")}`;
}

export function createToolRegistry() {
  const reg = new ToolRegistry();

  reg.register({ name:"generate_cue_sheet", description:"Generate a mixtape cue sheet (.cue and/or .txt) from the Set's REAL cue points — times computed from beats at the current tempo, files written to storage", category:"export", parameters:{ title:{type:"string",description:"Mix title (default: Set name)",required:false}, performer:{type:"string",description:"Performer/DJ name",required:false}, audio_file:{type:"string",description:"Audio file name the .cue references (default mixtape.wav)",required:false}, format:{type:"string",description:"Which files to write",required:false,enum:["cue","txt","both"]} } },
    async (args: any, song: any) => {
      const cues = [...(song?.cuePoints || [])].sort((a: any, b: any) => a.time - b.time);
      if (!cues.length) return { success:false, error:"No cue points in the Set — add markers first (arrangement__add_marker)." };
      const tempo = song?.tempo || 120;
      const secPerBeat = 60 / tempo;
      const title = args.title || song?.name || "Mixtape";
      const performer = args.performer || "Unknown Artist";
      const audioFile = args.audio_file || "mixtape.wav";
      const format = args.format || "both";

      const tracks = cues.map((c: any, i: number) => ({ n: i + 1, name: c.name || `Track ${i + 1}`, sec: c.time * secPerBeat }));

      let cueText = `REM GENRE Mixtape\nREM COMMENT "Generated by Live Studio (fixed tempo ${tempo} BPM)"\nPERFORMER "${performer}"\nTITLE "${title}"\nFILE "${audioFile}" WAVE\n`;
      for (const t of tracks) {
        cueText += `  TRACK ${String(t.n).padStart(2, "0")} AUDIO\n    TITLE "${t.name}"\n    PERFORMER "${performer}"\n    INDEX 01 ${fmtCue(t.sec)}\n`;
      }
      let txtText = `${title} — ${performer}\nTempo: ${tempo} BPM (fixed-tempo mapping)\n\n`;
      for (const t of tracks) txtText += `${fmtTxt(t.sec)}  ${String(t.n).padStart(2, "0")}. ${t.name}\n`;

      const dir = join(getStorageDir(), "cuesheets");
      if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
      const stamp = Date.now();
      const files: { format: string; path: string }[] = [];
      if (format === "cue" || format === "both") { const p = join(dir, `cuesheet_${stamp}.cue`); writeFileSync(p, cueText); files.push({ format: "cue", path: p }); }
      if (format === "txt" || format === "both") { const p = join(dir, `cuesheet_${stamp}.txt`); writeFileSync(p, txtText); files.push({ format: "txt", path: p }); }

      return { success:true, data:{ title, performer, tempo, tracks: tracks.map((t) => ({ n:t.n, name:t.name, time:fmtTxt(t.sec) })), files, note:"Times use a fixed-tempo beats→seconds mapping — the SDK doesn't expose tempo automation." } };
    }
  );

  return reg;
}
