// AUTO-GENERATED by scripts/gen-demo-tools.py — do not edit by hand.
// A tool is listed here when its handler returns simulated data (Math.random)
// without performing a real SDK operation. The UI badges these as "demo".
// Regenerate with: npm run gen:demo

export const DEMO_TOOLS: ReadonlySet<string> = new Set([
]);
