// Curated quick actions — each routes to a REAL tool with preset args.
// Generated; shell.js runs `tool` with `args` via /api/execute.
export interface QuickAction { group: string; name: string; tool: string; args: Record<string, unknown>; }
export const QUICK_ACTIONS: QuickAction[] = [
  { group:"Tempo", name:"90 BPM", tool:"temposync__set_tempo", args:{"bpm": 90} },
  { group:"Tempo", name:"100 BPM", tool:"temposync__set_tempo", args:{"bpm": 100} },
  { group:"Tempo", name:"110 BPM", tool:"temposync__set_tempo", args:{"bpm": 110} },
  { group:"Tempo", name:"120 BPM", tool:"temposync__set_tempo", args:{"bpm": 120} },
  { group:"Tempo", name:"124 BPM", tool:"temposync__set_tempo", args:{"bpm": 124} },
  { group:"Tempo", name:"128 BPM", tool:"temposync__set_tempo", args:{"bpm": 128} },
  { group:"Tempo", name:"140 BPM", tool:"temposync__set_tempo", args:{"bpm": 140} },
  { group:"Tempo", name:"150 BPM", tool:"temposync__set_tempo", args:{"bpm": 150} },
  { group:"Tempo", name:"174 BPM", tool:"temposync__set_tempo", args:{"bpm": 174} },
  { group:"Tempo", name:"Tap tempo", tool:"tempotap__tap", args:{} },
  { group:"Tempo", name:"Tempo info", tool:"temposync__get_tempo_info", args:{} },
  { group:"Create", name:"MIDI track", tool:"session__create_midi_track", args:{} },
  { group:"Create", name:"Audio track", tool:"session__create_audio_track", args:{} },
  { group:"Create", name:"Performance scene", tool:"performance__create_performance_scene", args:{"name": "Scene"} },
  { group:"Chords", name:"Pop in C", tool:"chords__generate_chords", args:{"key": "C", "scale": "major", "genre": "pop"} },
  { group:"Chords", name:"Pop in A minor", tool:"chords__generate_chords", args:{"key": "A", "scale": "minor", "genre": "pop"} },
  { group:"Chords", name:"Blues in C minor", tool:"chords__generate_chords", args:{"key": "C", "scale": "minor", "genre": "blues"} },
  { group:"Chords", name:"Jazz in F", tool:"chords__generate_chords", args:{"key": "F", "scale": "major", "genre": "jazz"} },
  { group:"Chords", name:"Rock in E minor", tool:"chords__generate_chords", args:{"key": "E", "scale": "minor", "genre": "rock"} },
  { group:"Chords", name:"Epic in G minor", tool:"chords__generate_chords", args:{"key": "G", "scale": "minor", "genre": "epic"} },
  { group:"Drums", name:"Techno beat", tool:"drums__generate_pattern", args:{"genre": "techno"} },
  { group:"Drums", name:"House beat", tool:"drums__generate_pattern", args:{"genre": "house"} },
  { group:"Drums", name:"Hip-Hop beat", tool:"drums__generate_pattern", args:{"genre": "hiphop"} },
  { group:"Drums", name:"Drum & Bass", tool:"drums__generate_pattern", args:{"genre": "dnb"} },
  { group:"Drums", name:"Trap beat", tool:"drums__generate_pattern", args:{"genre": "trap"} },
  { group:"Drums", name:"Latin beat", tool:"drums__generate_pattern", args:{"genre": "latin"} },
  { group:"Melody", name:"Melody in A minor (2 bars)", tool:"melody__generate_melody", args:{"key": "A", "scale": "minor", "bars": 2} },
  { group:"Melody", name:"Melody in C major (4 bars)", tool:"melody__generate_melody", args:{"key": "C", "scale": "major", "bars": 4} },
  { group:"Transpose", name:"Transpose +12", tool:"miditransform__transpose", args:{"track_index": 0, "clip_index": 0, "semitones": 12} },
  { group:"Transpose", name:"Transpose -12", tool:"miditransform__transpose", args:{"track_index": 0, "clip_index": 0, "semitones": -12} },
  { group:"Transpose", name:"Transpose +7 (fifth)", tool:"miditransform__transpose", args:{"track_index": 0, "clip_index": 0, "semitones": 7} },
  { group:"Transpose", name:"Transpose +5 (fourth)", tool:"miditransform__transpose", args:{"track_index": 0, "clip_index": 0, "semitones": 5} },
  { group:"Transpose", name:"Transpose +1", tool:"miditransform__transpose", args:{"track_index": 0, "clip_index": 0, "semitones": 1} },
  { group:"Transpose", name:"Transpose -1", tool:"miditransform__transpose", args:{"track_index": 0, "clip_index": 0, "semitones": -1} },
  { group:"Quantize", name:"Quantize 1/16", tool:"miditransform__quantize", args:{"track_index": 0, "clip_index": 0, "grid": "1/16"} },
  { group:"Quantize", name:"Quantize 1/8", tool:"miditransform__quantize", args:{"track_index": 0, "clip_index": 0, "grid": "1/8"} },
  { group:"Quantize", name:"Quantize 1/4", tool:"miditransform__quantize", args:{"track_index": 0, "clip_index": 0, "grid": "1/4"} },
  { group:"Transform", name:"Humanize notes", tool:"miditransform__humanize", args:{"track_index": 0, "clip_index": 0} },
  { group:"Transform", name:"Reverse notes", tool:"miditransform__reverse", args:{"track_index": 0, "clip_index": 0} },
  { group:"Transform", name:"Invert notes", tool:"miditransform__invert", args:{"track_index": 0, "clip_index": 0} },
  { group:"Arp", name:"Arpeggiate up", tool:"miditransform__apply_arpeggio", args:{"track_index": 0, "clip_index": 0, "pattern": "up"} },
  { group:"Arp", name:"Arpeggiate down", tool:"miditransform__apply_arpeggio", args:{"track_index": 0, "clip_index": 0, "pattern": "down"} },
  { group:"Arp", name:"Arpeggiate up-down", tool:"miditransform__apply_arpeggio", args:{"track_index": 0, "clip_index": 0, "pattern": "updown"} },
  { group:"Randomize", name:"Velocity", tool:"randomizer__randomize_velocity", args:{"track_index": 0, "clip_index": 0} },
  { group:"Randomize", name:"Pitch", tool:"randomizer__randomize_pitch", args:{"track_index": 0, "clip_index": 0} },
  { group:"Randomize", name:"Timing", tool:"randomizer__randomize_timing", args:{"track_index": 0, "clip_index": 0} },
  { group:"Randomize", name:"All params", tool:"randomizer__randomize_all", args:{"track_index": 0, "clip_index": 0} },
  { group:"Swing", name:"Hip-hop swing", tool:"quantizer__apply_swing", args:{"track_index": 0, "clip_index": 0, "preset": "hip-hop"} },
  { group:"Swing", name:"Shuffle", tool:"quantizer__apply_swing", args:{"track_index": 0, "clip_index": 0, "preset": "shuffle"} },
  { group:"Swing", name:"House swing", tool:"quantizer__apply_swing", args:{"track_index": 0, "clip_index": 0, "preset": "house"} },
  { group:"Swing", name:"Jazz swing", tool:"quantizer__apply_swing", args:{"track_index": 0, "clip_index": 0, "preset": "jazz"} },
  { group:"Groove", name:"Extract groove", tool:"groove__extract_groove", args:{"track_index": 0, "clip_index": 0} },
  { group:"Groove", name:"Apply groove", tool:"groove__apply_groove", args:{"track_index": 0, "clip_index": 0} },
  { group:"Color", name:"By velocity", tool:"colorizer__color_by_velocity", args:{"track_index": 0, "scheme": "heatmap"} },
  { group:"Color", name:"By pitch", tool:"colorizer__color_by_pitch", args:{"track_index": 0} },
  { group:"Color", name:"Clear colors", tool:"colorizer__clear_clip_colors", args:{"track_index": 0} },
  { group:"Step Seq", name:"8-step pattern", tool:"stepseq__set_pattern", args:{"steps": 8} },
  { group:"Step Seq", name:"16-step pattern", tool:"stepseq__set_pattern", args:{"steps": 16} },
  { group:"Step Seq", name:"32-step pattern", tool:"stepseq__set_pattern", args:{"steps": 32} },
  { group:"EQ", name:"Warm", tool:"eq__apply_eq_preset", args:{"track_index": 0, "preset": "warm"} },
  { group:"EQ", name:"Bright", tool:"eq__apply_eq_preset", args:{"track_index": 0, "preset": "bright"} },
  { group:"EQ", name:"Bass cut", tool:"eq__apply_eq_preset", args:{"track_index": 0, "preset": "bass_cut"} },
  { group:"EQ", name:"Smile", tool:"eq__apply_eq_preset", args:{"track_index": 0, "preset": "smile"} },
  { group:"Mixer", name:"Mute track 1", tool:"mixconsole__toggle_mute", args:{"track_index": 0} },
  { group:"Mixer", name:"Solo track 1", tool:"mixconsole__toggle_solo", args:{"track_index": 0} },
  { group:"Mixer", name:"Match levels", tool:"mastering__match_levels", args:{"track_indices": "0,1,2"} },
  { group:"State", name:"Save snapshot", tool:"snapshots__save_snapshot", args:{"name": "Snapshot"} },
  { group:"State", name:"Save mix scene", tool:"mixscene__save_scene", args:{"name": "Mix"} },
  { group:"State", name:"Add marker", tool:"arrangement__add_marker", args:{"name": "Marker", "time": 0} },
  { group:"Analyze", name:"Session summary", tool:"organizer__get_session_summary", args:{} },
  { group:"Analyze", name:"Session structure", tool:"organizer__analyze_session_structure", args:{} },
  { group:"Analyze", name:"Gain structure", tool:"mastering__analyze_gain_structure", args:{} },
  { group:"Analyze", name:"Mixer state", tool:"mixconsole__get_mixer_state", args:{} },
  { group:"Analyze", name:"Clip notes (trk 1)", tool:"notation__get_clip_notes", args:{"track_index": 0, "clip_index": 0} },
  { group:"Analyze", name:"Clip graph", tool:"clipgraph__build_graph", args:{} },
  { group:"Analyze", name:"Arrangement markers", tool:"arrangement__get_markers", args:{} },
  { group:"Analyze", name:"Arrangement sections", tool:"sections__get_sections", args:{} },
  { group:"Analyze", name:"Group routing", tool:"grouprouting__list_groups", args:{} },
  { group:"Analyze", name:"Drum rack (trk 1)", tool:"drummap__get_drum_rack", args:{"track_index": 0} },
  { group:"Analyze", name:"Takes (trk 1)", tool:"takes__list_takes", args:{"track_index": 0} },
  { group:"Analyze", name:"Time signature", tool:"timesig__get_time_signature", args:{} },
  { group:"Analyze", name:"Launch quantization", tool:"launchquant__get_global_quant", args:{} },
  { group:"Analyze", name:"Session info", tool:"session__get_session_info", args:{} },
  { group:"Analyze", name:"All tracks", tool:"session__get_all_tracks", args:{} },
];
