#!/usr/bin/env python3
"""Classify each tool as `demo` (simulated output) vs real, and emit a generated set.

A tool is `demo` when its handler fabricates its result with Math.random() and does
NOT perform a real SDK operation (create/insert/setValue/delete on song/track/clip).
Tools that mutate or read real Live state — even if they sprinkle random into a
response field — are treated as real.

Output: src/registry/demo-tools.ts  (a Set of fully-qualified `<moduleId>__<name>`).
Re-run with:  npm run gen:demo
"""
import glob
import os
import re

# Markers that a handler does real SDK work (-> NOT a demo, regardless of random).
REAL_OPS = re.compile(
    r"""\.(createMidiTrack|createAudioTrack|createScene|createGroupTrack|insertDevice|"""
    r"""createMidiClip|createAudioClip|createTakeLane|createCuePoint|setValue|deleteDevice|"""
    r"""duplicateDevice|deleteTrack|deleteScene|deleteClip|fire|stop|setNotes|applyNotes|"""
    r"""addNote|removeNotes)\("""
)
RANDOM = re.compile(r"Math\.random\(")

demo = []
real = 0
for f in sorted(glob.glob("src/modules/*/tools.ts")):
    mod = os.path.basename(os.path.dirname(f))
    src = open(f, encoding="utf-8").read()
    for chunk in re.split(r"reg\.register\(", src)[1:]:
        mname = re.search(r'name\s*:\s*"([a-z_][a-z0-9_]*)"', chunk)
        if not mname:
            continue
        name = mname.group(1)
        # body = everything after the definition object's first handler arrow
        marrow = re.search(r"=>", chunk)
        body = chunk[marrow.end():] if marrow else chunk
        is_demo = bool(RANDOM.search(body)) and not REAL_OPS.search(body)
        if is_demo:
            demo.append(f"{mod}__{name}")
        else:
            real += 1

demo = sorted(set(demo))
out = (
    "// AUTO-GENERATED by scripts/gen-demo-tools.py — do not edit by hand.\n"
    "// A tool is listed here when its handler returns simulated data (Math.random)\n"
    "// without performing a real SDK operation. The UI badges these as \"demo\".\n"
    "// Regenerate with: npm run gen:demo\n\n"
    f"export const DEMO_TOOLS: ReadonlySet<string> = new Set([\n"
    + "".join(f'  "{n}",\n' for n in demo)
    + "]);\n"
)
os.makedirs("src/registry", exist_ok=True)
open("src/registry/demo-tools.ts", "w", encoding="utf-8").write(out)
print(f"demo tools: {len(demo)}  |  real tools: {real}  |  total: {len(demo) + real}")
